name = "PlasmaTrace"
uuid = "e7da4491-aeb9-4b10-9e00-ae2014295cf4"
authors = ["Pieter Vermeesch <p.vermeesch@ucl.ac.uk>", "Jarred C. Lloyd <jarred.lloyd@adelaide.edu.au>"]
version = "0.0.1-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
